In [1]:
import pandas as pd

import numpy as np

In [2]:
df = pd.read_csv("matches.csv")
df.head()

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,Match Report,Notes,Sh,SoT,Dist,FK,PK,PKatt,Season,Team
0,2023-08-12,12:30,Premier League,Matchweek 1,Sat,Home,W,2.0,1.0,Nott'ham Forest,...,Match Report,NaN,15.0,7.0,19.1,0.0,0,0,2024,Arsenal
1,2023-08-21,20:00,Premier League,Matchweek 2,Mon,Away,W,1.0,0.0,Crystal Palace,...,Match Report,NaN,13.0,2.0,16.4,0.0,1,1,2024,Arsenal
2,2023-08-26,15:00,Premier League,Matchweek 3,Sat,Home,D,2.0,2.0,Fulham,...,Match Report,NaN,18.0,9.0,13.8,0.0,1,1,2024,Arsenal
3,2023-09-03,16:30,Premier League,Matchweek 4,Sun,Home,W,3.0,1.0,Manchester Utd,...,Match Report,NaN,17.0,5.0,15.0,0.0,0,0,2024,Arsenal
4,2023-09-17,16:30,Premier League,Matchweek 5,Sun,Away,W,1.0,0.0,Everton,...,Match Report,NaN,13.0,4.0,17.4,0.0,0,0,2024,Arsenal

In [3]:
df.shape

(1876, 27)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1876 entries, 0 to 1875
Data columns (total 27 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          1876 non-null   object
 1   Time          1876 non-null   object
 2   Comp          1876 non-null   object
 3   Round         1876 non-null   object
 4   Day           1876 non-null   object
 5   Venue         1876 non-null   object
 6   Result        1876 non-null   object
 7   GF            1876 non-null   float64
 8   GA            1876 non-null   float64
 9   Opponent      1876 non-null   object
 10  xG            1876 non-null   float64
 11  xGA           1876 non-null   float64
 12  Poss          1876 non-null   float64
 13  Attendance    1866 non-null   float64
 14  Captain       1876 non-null   object
 15  Formation     1876 non-null   object
 16  Referee       1876 non-null   object
 17  Match Report  1876 non-null   object
 18  Notes         0 non-null      float64
 19  Sh            1876 non-null   float64
 20  SoT           1876 non-null   float64
 21  Dist          1876 non-null   float64
 22  FK            1876 non-null   float64
 23  PK            1876 non-null   int64
 24  PKatt         1876 non-null   int64
 25  Season        1876 non-null   int64
 26  Team          1876 non-null   object
dtypes: float64(11), int64(3), object(13)
memory usage: 395.8+ KB

In [5]:
df["Match Report"].value_counts()

Match Report    1876
Name: Match Report, dtype: int64

In [6]:
df["Team"].value_counts()

Arsenal                     94
Manchester United           94
Everton                     94
Crystal Palace              94
Liverpool                   94
Wolverhampton Wanderers     94
Brighton and Hove Albion    94
Chelsea                     94
Newcastle United            94
West Ham United             94
Tottenham Hotspur           94
Aston Villa                 94
Manchester City             93
Brentford                   93
Southampton                 76
Leeds United                76
Leicester City              76
Burnley                     56
Fulham                      56
Nottingham Forest           56
Bournemouth                 55
Watford                     38
Norwich City                38
Sheffield United            18
Luton Town                  17
Name: Team, dtype: int64

In [7]:
df.duplicated().sum()

0

In [10]:
df["Date"] = pd.to_datetime(df["Date"])

In [11]:
df_2024 = df[df["Season"] == 2024]

In [22]:
df = df.sort_values(by="Date").reset_index(drop=True)

In [23]:
df

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,Match Report,Notes,Sh,SoT,Dist,FK,PK,PKatt,Season,Team
0,2021-08-13,20:00,Premier League,Matchweek 1,Fri,Away,L,0.0,2.0,Brentford,...,Match Report,NaN,22.0,4.0,19.0,1.0,0,0,2022,Arsenal
1,2021-08-13,20:00,Premier League,Matchweek 1,Fri,Home,W,2.0,0.0,Arsenal,...,Match Report,NaN,8.0,3.0,12.1,0.0,0,0,2022,Brentford
2,2021-08-14,15:00,Premier League,Matchweek 1,Sat,Home,W,3.0,0.0,Crystal Palace,...,Match Report,NaN,13.0,6.0,21.0,4.0,0,0,2022,Chelsea
3,2021-08-14,15:00,Premier League,Matchweek 1,Sat,Away,W,2.0,1.0,Burnley,...,Match Report,NaN,14.0,6.0,14.9,1.0,0,0,2022,Brighton and Hove Albion
4,2021-08-14,15:00,Premier League,Matchweek 1,Sat,Home,W,1.0,0.0,Wolves,...,Match Report,NaN,9.0,5.0,17.1,0.0,0,0,2022,Leicester City
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1871,2023-12-23,15:00,Premier League,Matchweek 18,Sat,Away,L,0.0,1.0,Luton Town,...,Match Report,NaN,15.0,2.0,12.2,0.0,0,0,2024,Newcastle United
1872,2023-12-23,15:00,Premier League,Matchweek 18,Sat,Home,L,0.0,2.0,Burnley,...,Match Report,NaN,19.0,5.0,16.3,1.0,0,0,2024,Fulham
1873,2023-12-23,15:00,Premier League,Matchweek 18,Sat,Home,L,2.0,3.0,Bournemouth,...,Match Report,NaN,11.0,4.0,14.5,0.0,0,0,2024,Nottingham Forest
1874,2023-12-24,13:00,Premier League,Matchweek 18,Sun,Away,L,1.0,2.0,Wolves,...,Match Report,NaN,16.0,4.0,17.4,1.0,0,0,2024,Chelsea
1875,2023-12-24,13:00,Premier League,Matchweek 18,Sun,Home,W,2.0,1.0,Chelsea,...,Match Report,NaN,14.0,6.0,16.7,1.0,0,0,2024,Wolverhampton Wanderers