In [24]:
import requests

import pandas as pd

from bs4 import BeautifulSoup

import time

pd.set_option('display.max_columns', 50)

In [2]:
years = list(range(2024,2021, -1))
years

[2024, 2023, 2022]

In [3]:
stats_url = "https://fbref.com/en/comps/9/Premier-League-Stats"

In [6]:
data = requests.get(stats_url)

In [9]:
data

In [7]:
soup = BeautifulSoup(data.text)

In [13]:
stats_table = pd.read_html(data.text, match="Regular season Table")[0]

In [14]:
stats_table

,Rk,Squad,MP,W,D,L,GF,GA,GD,Pts,Pts/MP,xG,xGA,xGD,xGD/90,Last 5,Attendance,Top Team Scorer,Goalkeeper,Notes
0,1,Liverpool,20,13,6,1,43,18,25,45,2.25,44.1,22.6,21.5,1.08,W D D W W,46872,Mohamed Salah - 14,Alisson,NaN
1,2,Aston Villa,20,13,3,4,43,27,16,42,2.10,36.0,25.6,10.3,0.52,W W D L W,28969,Ollie Watkins - 9,Emiliano Martínez,NaN
2,3,Manchester City,19,12,4,3,45,21,24,40,2.11,36.8,17.8,18.9,1.00,L W D W W,47396,Erling Haaland - 14,Ederson,NaN
3,4,Arsenal,20,12,4,4,37,20,17,40,2.00,36.4,16.3,20.0,1.00,L W D L L,60169,Bukayo Saka - 6,David Raya,NaN
4,5,Tottenham,20,12,3,5,42,29,13,39,1.95,35.2,34.7,0.4,0.02,W W W L W,61624,Son Heung-min - 12,Guglielmo Vicario,NaN
5,6,West Ham,20,10,4,6,33,30,3,34,1.70,27.7,35.2,-7.5,-0.38,L W W W D,62660,Jarrod Bowen - 11,Alphonse Areola,NaN
6,7,Brighton,20,8,7,5,38,33,5,31,1.55,35.0,29.6,5.4,0.27,D L D W D,31604,João Pedro - 7,Jason Steele,NaN
7,8,Manchester Utd,20,10,1,9,22,27,-5,31,1.55,29.1,32.5,-3.4,-0.17,L D L W L,73514,Scott McTominay - 5,André Onana,NaN
8,9,Newcastle Utd,20,9,2,9,39,29,10,29,1.45,39.2,33.5,5.7,0.29,L W L L L,52086,Alexander Isak - 9,Nick Pope,NaN
9,10,Chelsea,20,8,4,8,34,31,3,28,1.40,39.4,28.8,10.6,0.53,L W L W W,39720,Cole Palmer - 8,Robert Sánchez,NaN
10,11,Wolves,20,8,4,8,30,31,-1,28,1.40,26.6,33.1,-6.5,-0.32,D L W W W,31390,Hwang Hee-chan - 10,José Sá,NaN
11,12,Bournemouth,19,7,4,8,28,35,-7,25,1.32,27.0,31.4,-4.3,-0.23,W W W W L,11027,Dominic Solanke - 12,Neto,NaN
12,13,Fulham,20,7,3,10,28,35,-7,24,1.20,24.4,34.3,-9.9,-0.50,W L L L W,24243,Raúl Jiménez - 5,Bernd Leno,NaN
13,14,Crystal Palace,20,5,6,9,22,29,-7,21,1.05,24.6,28.6,-4.0,-0.20,L D D L W,24902,Odsonne Édouard - 6,Sam Johnstone,NaN
14,15,Nott'ham Forest,20,5,5,10,24,35,-11,20,1.00,23.8,30.8,-7.0,-0.35,D L L W W,29289,Chris Wood - 7,Matt Turner,NaN
15,16,Brentford,19,5,4,10,26,31,-5,19,1.00,32.6,25.2,7.3,0.39,L L L L L,17057,Bryan Mbeumo - 7,Mark Flekken,NaN
16,17,Everton,20,8,2,10,24,28,-4,16,0.80,30.1,27.7,2.4,0.12,W W L L L,39086,Abdoulaye Doucouré - 6,Jordan Pickford,10-point deduction 1
17,18,Luton Town,19,4,3,12,23,37,-14,15,0.79,19.2,38.5,-19.3,-1.02,L L W W L,9810,Elijah Adebayo - 5,Thomas Kaminski,NaN
18,19,Burnley,20,3,2,15,20,41,-21,11,0.55,17.4,34.5,-17.0,-0.85,D L W L L,21557,Lyle Foster - 4,James Trafford,NaN
19,20,Sheffield Utd,20,2,3,15,15,49,-34,9,0.45,16.2,39.9,-23.7,-1.18,W L D L L,30694,"Oliver McBurnie, Cameron Archer - 3",Wes Foderingham,NaN

In [15]:
standard_stats = pd.read_html(data.text, match = "Squad Standard Stats")[0]

   Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                Squad               # Pl                Age
0             Arsenal                 23               25.3
1         Aston Villa                 26               27.4
2         Bournemouth                 25               26.1
3           Brentford                 26               27.0
4            Brighton                 27               26.7
5             Burnley                 26               25.3
6             Chelsea                 28               25.0
7      Crystal Palace                 24               27.6
8             Everton                 25               27.4
9              Fulham                 24               29.3
10          Liverpool                 23               27.2
11         Luton Town                 23               27.2
12    Manchester City                 25               27.0
13     Manchester Utd                 29               27.0
14      Newcastle Utd                 30               27.9
15    Nott'ham Forest                 28               26.5
16      Sheffield Utd                 29               26.6
17          Tottenham                 25               25.7
18           West Ham                 23               28.8
19             Wolves                 23               27.2

   Unnamed: 3_level_0 Playing Time                    Performance      ...  \
                 Poss           MP Starts   Min   90s         Gls Ast  ...
0                60.3           20    220  1800  20.0          36  23  ...
1                54.6           20    220  1800  20.0          40  30  ...
2                44.2           19    209  1768  19.6          28  20  ...
3                48.3           19    209  1710  19.0          25  16  ...
4                61.1           20    220  1800  20.0          36  28  ...
5                47.6           20    220  1800  20.0          20  17  ...
6                59.2           20    220  1800  20.0          33  21  ...
7                42.9           20    220  1800  20.0          22  17  ...
8                39.5           20    220  1800  20.0          24  11  ...
9                50.1           20    220  1800  20.0          27  17  ...
10               60.2           20    220  1800  20.0          40  30  ...
11               37.4           19    209  1768  19.6          20  14  ...
12               63.6           19    209  1710  19.0          44  32  ...
13               52.8           20    220  1800  20.0          22  15  ...
14               54.6           20    220  1800  20.0          39  26  ...
15               39.7           20    220  1800  20.0          24  21  ...
16               36.2           20    220  1800  20.0          12   7  ...
17               59.2           20    220  1800  20.0          39  34  ...
18               40.6           20    220  1800  20.0          32  25  ...
19               47.8           20    220  1800  20.0          29  24  ...

   Per 90 Minutes
              Gls   Ast   G+A  G-PK G+A-PK    xG   xAG xG+xAG  npxG npxG+xAG
0            1.80  1.15  2.95  1.50   2.65  1.82  1.21   3.03  1.59     2.80
1            2.00  1.50  3.50  1.80   3.30  1.80  1.33   3.13  1.64     2.98
2            1.43  1.02  2.44  1.37   2.39  1.38  0.98   2.35  1.34     2.31
3            1.32  0.84  2.16  1.16   2.00  1.71  1.22   2.94  1.60     2.83
4            1.80  1.40  3.20  1.60   3.00  1.75  1.30   3.05  1.61     2.91
5            1.00  0.85  1.85  0.95   1.80  0.87  0.67   1.55  0.83     1.51
6            1.65  1.05  2.70  1.35   2.40  1.97  1.27   3.24  1.70     2.97
7            1.10  0.85  1.95  0.95   1.80  1.23  0.96   2.19  1.11     2.08
8            1.20  0.55  1.75  1.20   1.75  1.50  1.12   2.62  1.50     2.62
9            1.35  0.85  2.20  1.25   2.10  1.22  0.84   2.06  1.14     1.98
10           2.00  1.50  3.50  1.80   3.30  2.21  1.60   3.81  1.96     3.56
11           1.02  0.71  1.73  0.92   1.63  0.98  0.69   1.67  0.90     1.59
12           2.32  1.68  4.00  2.11   3.79  1.94  1.48   3.41  1.74     3.22
13           1.10  0.75  1.85  1.00   1.75  1.46  1.07   2.53  1.34     2.41
14           1.95  1.30  3.25  1.75   3.05  1.96  1.31   3.28  1.80     3.12
15           1.20  1.05  2.25  1.15   2.20  1.19  0.90   2.09  1.15     2.05
16           0.60  0.35  0.95  0.50   0.85  0.81  0.49   1.30  0.73     1.22
17           1.95  1.70  3.65  1.90   3.60  1.76  1.52   3.27  1.72     3.23
18           1.60  1.25  2.85  1.55   2.80  1.38  0.93   2.31  1.30     2.23
19           1.45  1.20  2.65  1.40   2.60  1.33  0.98   2.31  1.29     2.27

[20 rows x 32 columns]

In [16]:
standard_stats.columns = standard_stats.columns.droplevel()

In [25]:
standard_stats

,Squad,# Pl,Age,Poss,MP,Starts,Min,90s,Gls,Ast,G+A,G-PK,PK,PKatt,CrdY,CrdR,xG,npxG,xAG,npxG+xAG,PrgC,PrgP,Gls,Ast,G+A,G-PK,G+A-PK,xG,xAG,xG+xAG,npxG,npxG+xAG
0,Arsenal,23,25.3,60.3,20,220,1800,20.0,36,23,59,30,6,6,32,2,36.4,31.9,24.2,56.0,441,1142,1.80,1.15,2.95,1.50,2.65,1.82,1.21,3.03,1.59,2.80
1,Aston Villa,26,27.4,54.6,20,220,1800,20.0,40,30,70,36,4,4,55,1,36.0,32.9,26.7,59.6,436,839,2.00,1.50,3.50,1.80,3.30,1.80,1.33,3.13,1.64,2.98
2,Bournemouth,25,26.1,44.2,19,209,1768,19.6,28,20,48,27,1,1,35,1,27.0,26.2,19.2,45.4,330,620,1.43,1.02,2.44,1.37,2.39,1.38,0.98,2.35,1.34,2.31
3,Brentford,26,27.0,48.3,19,209,1710,19.0,25,16,41,22,3,3,42,1,32.6,30.4,23.3,53.7,261,697,1.32,0.84,2.16,1.16,2.00,1.71,1.22,2.94,1.60,2.83
4,Brighton,27,26.7,61.1,20,220,1800,20.0,36,28,64,32,4,4,51,2,35.0,32.1,26.0,58.1,475,1023,1.80,1.40,3.20,1.60,3.00,1.75,1.30,3.05,1.61,2.91
5,Burnley,26,25.3,47.6,20,220,1800,20.0,20,17,37,19,1,1,42,4,17.4,16.7,13.5,30.1,345,604,1.00,0.85,1.85,0.95,1.80,0.87,0.67,1.55,0.83,1.51
6,Chelsea,28,25.0,59.2,20,220,1800,20.0,33,21,54,27,6,7,65,3,39.4,33.9,25.4,59.3,464,836,1.65,1.05,2.70,1.35,2.40,1.97,1.27,3.24,1.70,2.97
7,Crystal Palace,24,27.6,42.9,20,220,1800,20.0,22,17,39,19,3,3,39,1,24.6,22.2,19.3,41.5,261,610,1.10,0.85,1.95,0.95,1.80,1.23,0.96,2.19,1.11,2.08
8,Everton,25,27.4,39.5,20,220,1800,20.0,24,11,35,24,0,0,45,1,30.1,30.1,22.4,52.5,272,599,1.20,0.55,1.75,1.20,1.75,1.50,1.12,2.62,1.50,2.62
9,Fulham,24,29.3,50.1,20,220,1800,20.0,27,17,44,25,2,2,49,3,24.4,22.8,16.7,39.5,331,775,1.35,0.85,2.20,1.25,2.10,1.22,0.84,2.06,1.14,1.98
10,Liverpool,23,27.2,60.2,20,220,1800,20.0,40,30,70,36,4,6,38,4,44.1,39.2,32.0,71.2,459,1078,2.00,1.50,3.50,1.80,3.30,2.21,1.60,3.81,1.96,3.56
11,Luton Town,23,27.2,37.4,19,209,1768,19.6,20,14,34,18,2,2,36,0,19.2,17.7,13.7,31.3,294,517,1.02,0.71,1.73,0.92,1.63,0.98,0.69,1.67,0.90,1.59
12,Manchester City,25,27.0,63.6,19,209,1710,19.0,44,32,76,40,4,5,35,2,36.8,33.1,28.1,61.1,532,937,2.32,1.68,4.00,2.11,3.79,1.94,1.48,3.41,1.74,3.22
13,Manchester Utd,29,27.0,52.8,20,220,1800,20.0,22,15,37,20,2,3,49,1,29.1,26.7,21.5,48.2,404,880,1.10,0.75,1.85,1.00,1.75,1.46,1.07,2.53,1.34,2.41
14,Newcastle Utd,30,27.9,54.6,20,220,1800,20.0,39,26,65,35,4,4,50,0,39.2,36.1,26.3,62.4,371,862,1.95,1.30,3.25,1.75,3.05,1.96,1.31,3.28,1.80,3.12
15,Nott'ham Forest,28,26.5,39.7,20,220,1800,20.0,24,21,45,23,1,1,48,3,23.8,23.0,17.9,40.9,291,566,1.20,1.05,2.25,1.15,2.20,1.19,0.90,2.09,1.15,2.05
16,Sheffield Utd,29,26.6,36.2,20,220,1800,20.0,12,7,19,10,2,2,65,2,16.2,14.6,9.7,24.4,166,432,0.60,0.35,0.95,0.50,0.85,0.81,0.49,1.30,0.73,1.22
17,Tottenham,25,25.7,59.2,20,220,1800,20.0,39,34,73,38,1,1,56,4,35.2,34.4,30.3,64.7,496,1070,1.95,1.70,3.65,1.90,3.60,1.76,1.52,3.27,1.72,3.23
18,West Ham,23,28.8,40.6,20,220,1800,20.0,32,25,57,31,1,2,47,1,27.7,26.1,18.6,44.7,273,635,1.60,1.25,2.85,1.55,2.80,1.38,0.93,2.31,1.30,2.23
19,Wolves,23,27.2,47.8,20,220,1800,20.0,29,24,53,28,1,1,54,3,26.6,25.8,19.7,45.5,362,623,1.45,1.20,2.65,1.40,2.60,1.33,0.98,2.31,1.29,2.27

In [18]:
goalkeeping_stats = pd.read_html(data.text, match="Squad Goalkeeping")[0]

In [20]:
goalkeeping_stats.columns = goalkeeping_stats.columns.droplevel()

In [29]:
goalkeeping_stats

,Squad,# Pl,MP,Starts,Min,90s,GA,GA90,SoTA,Saves,Save%,W,D,L,CS,CS%,PKatt,PKA,PKsv,PKm,Save%
0,Arsenal,2,20,20,1800,20.0,20,1.00,49,28,61.2,12,4,4,7,35.0,2,1,1,0,50.0
1,Aston Villa,2,20,20,1800,20.0,27,1.35,82,57,67.1,13,3,4,4,20.0,0,0,0,0,NaN
2,Bournemouth,2,19,19,1710,19.6,35,1.84,98,63,66.3,7,4,8,5,26.3,3,2,1,0,33.3
3,Brentford,2,19,19,1710,19.0,31,1.63,82,51,63.4,5,4,10,3,15.8,1,1,0,0,0.0
4,Brighton,2,20,20,1800,20.0,33,1.65,81,50,65.4,8,7,5,1,5.0,5,5,0,0,0.0
5,Burnley,1,20,20,1800,20.0,41,2.05,120,81,68.3,3,2,15,2,10.0,3,3,0,0,0.0
6,Chelsea,2,20,20,1800,20.0,31,1.55,97,65,70.1,8,4,8,4,20.0,3,2,1,0,33.3
7,Crystal Palace,3,20,20,1800,20.0,29,1.45,78,50,66.7,5,6,9,5,25.0,3,3,0,0,0.0
8,Everton,1,20,20,1800,20.0,28,1.40,79,53,70.9,8,2,10,6,30.0,5,5,0,0,0.0
9,Fulham,1,20,20,1800,20.0,35,1.75,108,76,72.2,7,3,10,5,25.0,5,5,0,0,0.0
10,Liverpool,2,20,20,1800,20.0,18,0.90,68,51,75.0,13,6,1,7,35.0,1,1,0,0,0.0
11,Luton Town,1,19,19,1710,19.6,37,1.95,107,71,66.4,4,3,12,1,5.3,1,1,0,0,0.0
12,Manchester City,2,19,19,1710,19.0,21,1.11,54,34,64.8,12,4,3,5,26.3,2,2,0,0,0.0
13,Manchester Utd,1,20,20,1800,20.0,27,1.35,95,69,73.7,10,1,9,6,30.0,2,2,0,0,0.0
14,Newcastle Utd,2,20,20,1800,20.0,29,1.45,99,69,72.7,9,2,9,7,35.0,3,2,1,0,33.3
15,Nott'ham Forest,2,20,20,1800,20.0,35,1.75,94,59,66.0,5,5,10,3,15.0,3,3,0,0,0.0
16,Sheffield Utd,1,20,20,1800,20.0,49,2.45,135,89,64.4,2,3,15,1,5.0,2,1,0,1,0.0
17,Tottenham,1,20,20,1800,20.0,29,1.45,91,64,73.6,12,3,5,5,25.0,5,5,0,0,0.0
18,West Ham,2,20,20,1800,20.0,30,1.50,108,78,75.0,10,4,6,5,25.0,4,3,1,0,25.0
19,Wolves,2,20,20,1800,20.0,31,1.55,89,59,70.8,8,4,8,3,15.0,5,5,0,0,0.0

In [22]:
shooting_stats = pd.read_html(data.text, match="Squad Shooting")[0]

In [27]:
#shooting_stats.columns = shooting_stats.columns.droplevel()
shooting_stats.head()

,Squad,# Pl,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG
0,Arsenal,23,20.0,36,319,98,30.7,15.95,4.90,0.09,0.31,16.0,2,6,6,36.4,31.9,0.10,-0.4,-1.9
1,Aston Villa,26,20.0,40,289,102,35.3,14.45,5.10,0.12,0.35,16.6,8,4,4,36.0,32.9,0.12,4.0,3.1
2,Bournemouth,25,19.6,28,254,89,35.0,12.93,4.53,0.11,0.30,16.3,8,1,1,27.0,26.2,0.11,1.0,0.8
3,Brentford,26,19.0,25,253,73,28.9,13.32,3.84,0.09,0.30,14.7,7,3,3,32.6,30.4,0.13,-7.6,-8.4
4,Brighton,27,20.0,36,305,123,40.3,15.25,6.15,0.10,0.26,16.6,9,4,4,35.0,32.1,0.11,1.0,-0.1